server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  # standalone mode
  client:
    registerWithEureka: false
    fetchRegistry: false
    enableSelfPreservation: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

---
spring:
  profiles: docker
  application:
    name: discovery-server
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    enableSelfPreservation: false

---
spring:
  profiles: discovery-server-0
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server-1.discovery-instance:8761/eureka


---
spring:
  profiles: discovery-server-1
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server-0.discovery-instance:8761/eureka
